name: expense_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.70.2
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_slidable: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/satoshi_font/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/satoshi_font/Satoshi-Light.otf
          weight: 300
        - asset: assets/satoshi_font/Satoshi-Regular.otf
          weight: 400
        - asset: assets/satoshi_font/Satoshi-Medium.otf
          weight: 600
        - asset: assets/satoshi_font/Satoshi-Bold.otf
          weight: 700
